#!/bin/sh
LC_ALL=C

commit_message="$(cat $1)"

valid_commit_message_regex="^(feature|fix|docs|style|refactor|test|chore): .+"

message="There is something wrong with your commit message. Message must adhere to this contract: $valid_commit_message_regex. You should change your commit message and try again."

echo "Verifying commit message.."

if [[ ! $commit_message =~ $valid_commit_message_regex ]]
then
    echo "$message"
    exit 1
fi

exit 0



